name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: kaiko-ai
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Lint
        run: nix-shell --run "sbt 'scalafix -r OrganizeImports --check'"
      - name: Test and build
        run: nix-build
      - uses: actions/upload-artifact@v2
        with:
          name: nix-build result JARs
          path: result/jars/
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Release Snapshot
        run: nix-shell --run "sbt 'publishSigned'"
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
