name: CI
on:
  pull_request:
  push:
jobs:
  check_skip:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["**/README.md"]'
          cancel_others: "true"
          skip_after_successful_duplicate: "true"
          concurrent_skipping: "same_content"
  build:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: kaiko-ai
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: build
        run: nix-build
