name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: kaiko-ai
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Test and build
        run: nix-build
      - uses: actions/upload-artifact@v2
        with:
          name: nix-build result JARs
          path: result/jars/
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: kaiko-ai
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Formatting (scalafmt)
        run: nix-shell --run "scalafmt --test"
      - name: Lint (scalafix)
        run: nix-shell --run "sbt 'scalafix -r OrganizeImports --check'"
  shellcheck:
    runs-on: ubuntu-latest
    container:
        image: koalaman/shellcheck-alpine:v0.8.0@sha256:7d818fda19f5d8658fbb61b53f106cde88eda4b977b1db916ad9d3ccfa1c3ac6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Shellcheck scripts
        run: ./scripts/shellcheck_all.sh
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check license headers
        run: ./scripts/check_license_headers.sh
